### PR TITLE
Opening more ports as some services don't seem to be exposed

### PR DESCRIPTION
**Pull request by schrepfler**
Opened more ports as per https://docs.datastax.com/en/latest-dse/datastax_enterprise/sec/configFirewallPorts.html

### CODE REVIEW

**Comment by schrepfler** [comment]
You don't need any changes from the script edits.  Apologies as I wanted to see if I can make my fork. I get the feeling that the scripts have issues with either OSX (BSD?) or zsh as I get some weird things like
```
> ./docker-build.sh
unable to prepare context: unable to evaluate symlinks in Dockerfile path: lstat /Users/schrepfler/Documents/sources/dse-docker/build/Dockerfile: no such file or directory
```

**Comment by LukeTillman** [comment]
Thanks for the PR! About the scripts, those are meant to be run from the root of the repository.
```
> ./build/docker-build.sh
```
I suspect that's why you're getting the errors (and I should probably update the `README` with build details). I'll work on just merging the `DOCKERFILE` changes from the PR.

**Comment by LukeTillman** [comment]
The 2 commits with `DOCKERFILE` changes have been merged. I went ahead and did a [subsequent commit][commit] where I removed a couple ports for OpsCenter and DataStax Studio which aren't installed as part of this image. The `5.0.4` image up on Docker Hub should have the changes now. Thanks again for the PR!

[commit]: https://github.com/LukeTillman/dse-docker/commit/b61b53b64f3de056bbdb952d6fff7d5e6e6cb039

**Comment by schrepfler** [comment]
No problems, thanks for the useful image!

**Pull request closed without merging**
